# DB
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sys?useSSL=false
    username: root
    password: Abc12345

# DOMA
doma:
  dialect: MYSQL
  naming: SNAKE_LOWER_CASE

# MARKET
bittrex:
  baseUrl: https://bittrex.com/api/v1.1/
  apiKey: 16dd768cc7584c73b0e54c4c7b7eca94
  secret: f4a4b8c6498240ba8966cb11e7dab9c8
  devMode: false

data-collector:
  # 999 for non-stop
  size: 998
  # milisecond
  delay: 500
